config/routes.rb
Rails.application.routes.draw do

  resources :contacts, except: [:show]
  resources :kinds

  root 'contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id      :bigint           not null, primary key
#  name    :string(255)
#  address :string(255)
#  phone   :integer
#  kind_id :bigint
#
class Contact < ApplicationRecord
  belongs_to :kind
end

app/models/kind.rb
# == Schema Information
#
# Table name: kinds
#
#  id          :bigint           not null, primary key
#  description :string(255)
#
class Kind < ApplicationRecord
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contacts_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: 'Sucesso' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update(contacts_params)
        format.html { redirect_to contacts_path, notice: 'Sucesso' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_path, notice: 'Foi deletado com sucesso!' }
    end
  end

  private

  def contacts_params
    params.require(:contact).permit(:name, :address, :phone, :kind_id)
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  def index
    @kinds = Kind.all
  end

  def new
    @kind = Kind.new
  end

  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to kinds_path, notice: 'Sucesso' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @kind = Kind.find(params[:id])
  end

  def update
    @kind = Kind.find(params[:id])

    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to kinds_path, notice: 'Sucesso' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @kind = Kind.find(params[:id])
    @kind.destroy

    respond_to do |format|
      format.html { redirect_to kinds_path, notice: 'Foi deletado com sucesso!'}
    end
  end

  private

  def kind_params
    params.require(:kind).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.slim
= form_with(model: contact, local: true) do |form|
  .table-create
    .form-create
      = form.label :name
      = form.text_field :name
    .form-create
      = form.label :phone
      = form.phone_field :phone
    .form-create.last
      = form.label :address
      = form.text_field :address
    .form-create.last
      = form.label :kind
      = form.collection_select(:kind_id, Kind.all, :id, :description )
  = form.submit contact.new_record? ? 'Adicionar' : 'Editar'

app/views/contacts/edit.html.slim
.body
  .container
    h2#title-new-contact
      | Edit Contact
    .background-form
      = render 'form', contact: @contact

app/views/contacts/index.html.slim
<!--     <%#= notice %> Testar esse comando depois-->

.body
  .container
    h1
      | Contact Book
    table.responsive-table
      thead
        tr.table-header
          th.col.col-1
            | Id
          th.col.col-2
            | Name
          th.col.col-3
            | Address
          th.col.col-4
            | Phone
          th.col.col-4
            | Kind
          th.col.col-5
            | Options
      tbody
        - @contacts.each do |contact|
          tr.table-row
            td.col.col-1
              = contact.id
            td.col.col-2
              = contact.name
            td.col.col-3 = contact.address
            td.col.col-4
              = contact.phone
            td.col.col-4
              = contact.kind.description
            td.col.col-5
              = link_to 'Delete', contact, class: 'button', method: :delete, data: {confirm: 'Você tem certeza?'}
              = link_to 'Edit', edit_contact_path(contact), class: 'button'

    .table-footer
      = link_to 'Novo', new_contact_path, class: 'b-new'

app/views/contacts/new.html.slim
.body
  .container
    h2#title-new-contact
      | New Contact
    .background-form
      = render 'form', contact: @contact

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true) do |form|  %>
  <div class="table-create">
    <div class="form-create">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>
  </div>



  <%= form.submit kind.new_record? ? 'Adicionar' : 'Editar'%>
<% end %>

app/views/kinds/edit.html.erb
<div class="body">
  <div class="container ">
    <h2 id="title-new-contact">Edit Kind</h2>
    <div class="background-form">
      <%= render 'form', kind: @kind %>
    </div>
  </div>
</div>

app/views/kinds/index.html.erb
<!--<h1>Agenda de Contatos</h1>-->
<!--<div class="container">-->


<!--<table>-->
<!--  <thead>-->
<!--<tr>-->
<!--<th>Nome</th>-->
<!--      <th>Endereço</th>-->
<!--      <th>Telefone</th>-->
<!--    </tr>-->
<!--  </thead>-->
<!--</table>-->

<!--</div>-->
<div class="body">
  <div class="container">
    <h1> List of Kinds </h1>
    <table class="responsive-table">
      <thead>
      <tr class="table-header">
        <th class="col col-1">Id</th>
        <th class="col col-2">Description</th>
        <th class="col col-5"></th>
      </tr>
      </thead>

      <tbody>
      <% @kinds.each do |kind| %>
        <tr class="table-row">
          <td class="col col-1"><%= kind.id %></td>
          <td class="col col-2"><%= kind.description %></td>
          <td class="col col-5">
            <%= link_to 'Excluir', kind, class: 'button', method: :delete, data: { confirm: 'Você tem certeza?'} %>
            <%= link_to 'Editar', edit_kind_path(kind), class: 'button' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <div class="table-footer">
      <%= link_to 'Novo', new_kind_path, class: 'b-new' %>
    </div>


  </div>
</div>

app/views/kinds/new.html.erb
<div class="body">
  <div class="container ">
    <h2 id="title-new-contact">New Kind</h2>
    <div class="background-form">
      <%= render 'form', kind: @kind %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul class="header">
    <li><%= link_to 'Contacts', contacts_path, class: 'button' %></li>
    <li><%= link_to 'Kinds', kinds_path, class: 'button' %></li>
  </ul>
    <%= yield %>
  </body>
</html>